### ISSUE TITLE
picture size in create customer screen

### ISSUE THREAD

**Issue by vrsumitha** [vrsumitha/maxmoney-agent#17]
- height: 200px;
- width: 350px;
- maxsize for upload image: 2MB

**Comment by vrsumitha** [comment]
done and merged to master

**Comment by munmin2000** [comment]
maxsize for image upload : 5mb

**Comment by donkhan** [comment]
Max Size for Image upload : 6MB
Make sure it is handled properly for Validation in all places.
Explore possibility of placing it as common in the controller.

**Comment by vrsumitha** [comment]
merged to master
