### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by munmin2000** [vrsumitha/maxmoney-agent#27]
- [x] Remove Validate Message when click on CDD **Next**
- [x] Third Screen Title to **Create Customer**
- [x] In Third Screen, Make the customer information in to Two columns
- [x] In Third Screen, Format DOB to DD-MM-YYYY
- [x] Image size : style="width: 600px; height: 300px"
- [x] Remove **"Your MaxMoney Id is xxxxxxxx"** in confirmation popup
- [x] Remove Customers link for Header **Max CDD Console**

**Comment by vrsumitha** [comment]
all done and merged with master

**Comment by munmin2000** [comment]
- [x] Put Mobile code as +6 (Malaysian Code) for all nationality
not working as expected

**Comment by vrsumitha** [comment]
done and merged to master

**Comment by munmin2000** [comment]
Do not change the Country Dialing code based on Nationality. Put +6 as Default for all Nationalities.

**Comment by munmin2000** [comment]
working as expected
