### ISSUE TITLE
Screen Improvements

### ISSUE THREAD

**Issue by donkhan** [vrsumitha/maxmoney-agent#31]
1. Show Name of the Customer and Passport No/IC No in the Upload Screen
2. Move Nature of Business and Source of Income to Upload Screen Page.
3. When User clicks the user name in the listing page (First Page of CDD Officer), then go to Upload screen directly. Do not show Edit Screen

**Comment by vrsumitha** [comment]
done and merged with master

**Comment by munmin2000** [comment]
In Third screen, Status shows as 200. Image not loading.

**Comment by munmin2000** [comment]
Image loading and status working as expected.

**Comment by donkhan** [comment]
Done
