### ISSUE TITLE
API Calls should go to api-maxmoney.com

### ISSUE THREAD

**Issue by donkhan** [vrsumitha/maxmoney-agent#32]
If Website is hosted in maxmoney.com then API calls should go api-maxmoney.com
Otherwise it should go to api-staging.maxmoney.com

**Comment by vrsumitha** [comment]
done. pull request created https://github.com/vrsumitha/maxmoney-agent/pull/64

**Comment by vrsumitha** [comment]
merge done

**Comment by munmin2000** [comment]
working as expected

**Comment by vrsumitha** [comment]
merged to master...
