### ISSUE TITLE
Rates Screen

### ISSUE THREAD

**Issue by donkhan** [vrsumitha/maxmoney-agent#42]
1. Screen Title - Transfer Rates
2. Access Control - Available only for Max CDD Officer
3. Screen Should contain a table with three columns
   a. Country
   b. Currency
   c. Transfer Rate
4. Currencies supported
1. php(philipines) 2. inr(India) 3. pkr (pakistan) 4. Indonesia (idr) 5. npr(Nepal) 

Example
https://api-staging.maxmoney.com:443/v1/boards/moos/rates/php
will give you {
  "php_order": "11",
  "php_buy_direction": "same",
  "php_sell_percent": "100",
  "php_tt_percent": "100",
  "php_buy_percent": "100",
  "php_sell": "8.85",
  "php_tt": "8.4034",
  "php_sell_direction": "same",
  "php_unit": "100",
  "php_decimal_places": "4",
  "php_name": "Philippine Peso",
  "php_time": "1495939843653",
  "php_denominator": "10",
  "php_tt_direction": "same",
  "php_buy": "8.62"
}

From this take php_tt as Rate, php_name as Name and country u know

**Comment by vrsumitha** [comment]
Done - Rates which has country keys are all shown.

**Comment by munmin2000** [comment]
@vrsumitha 
- [ ] Add last updated Date and Time
- [ ] resize the columns and center it

**Comment by vrsumitha** [comment]
done and ready for testing in this branch

**Comment by munmin2000** [comment]
```<div class="col-md-3">&nbsp;</div>```
add this line at 3 row
```4th line <div class="col-md-6 col-sm-12">```

**Comment by vrsumitha** [comment]
merged with master and working as expected from the master

**Comment by donkhan** [comment]
Done
