### ISSUE TITLE
Login Enhancement

### ISSUE THREAD

**Issue by donkhan** [vrsumitha/maxmoney-agent#43]
If user name contains @ symbol, leave as it is
If it does not contain @ symbol, append "@maxmoney.com" before sending to Back End.

User can avoid typing cdd@maxmoney.com, instead he can type cdd

**Comment by vrsumitha** [comment]
done and merged to master

**Comment by munmin2000** [comment]
tested. working as expected. Kindly Merge

**Comment by vrsumitha** [comment]
merged to master
