### ISSUE TITLE
Case InSenstiveness of Passport No

### ISSUE THREAD

**Issue by donkhan** [vrsumitha/maxmoney-agent#45]
Convert user typed Passport No to Upper case in First Page of CDD officer

**Comment by vrsumitha** [comment]
fixed and ready for testing

**Comment by munmin2000** [comment]
@vrsumitha 
System shows "Customer Not Found" for both match and non match passport entries.

**Comment by munmin2000** [comment]
working as expected

**Comment by vrsumitha** [comment]
merged to master
