### ISSUE TITLE
Cancel Button  on Every Screen

### ISSUE THREAD

**Issue by donkhan** [vrsumitha/maxmoney-agent#48]
Upload Page, Create Customer Page - Give Cancel Button - Should take you to Home Page

**Comment by vrsumitha** [comment]
done and ready for testing

**Comment by munmin2000** [comment]
MaxcddOfficer - Registration Landing Page
CddOfficer - Customer Search

**Comment by vrsumitha** [comment]
fixed and ready for testing

**Comment by munmin2000** [comment]
working as expected

**Comment by vrsumitha** [comment]
Merged to master.
tested from master, and it is working as expected

**Comment by donkhan** [comment]
Done
