### ISSUE TITLE
user search for maxCdd officer

### ISSUE THREAD

**Issue by vrsumitha** [vrsumitha/maxmoney-agent#67]

**Comment by donkhan** [comment]
End Point is /users/identification-document/{id}

**Comment by vrsumitha** [comment]
- removed unnecessary fields in user search page.
- updated the end point to search the user

**Comment by munmin2000** [comment]
- [x] Change 3 columns display to 2 columns
- [x] Add PID Number in the display
- [x] Hide add beneficiary

**Comment by vrsumitha** [comment]
done and code updated in the branch

**Comment by vrsumitha** [comment]
merged to master, I am closing this issue
