### ISSUE TITLE
Listing of Customers for CDD Officer

### ISSUE THREAD

**Issue by donkhan** [vrsumitha/maxmoney-agent#7]
1. This screen is the home screen for the users who has role as cdd officer.
2. Table with 4 columns a. Customer Name b. Registration Time c. Mobile d. Address
3. Hover link over Name
4. On clicking Name, Upload page should be shown. Based on ID Type either NRIC or Passport should be made uploadable. Reuse the existing code.
5. Give Approve option.
6. Once User approved it, Process ends. Take him back to listing page.

**Comment by vrsumitha** [comment]
done and merged to master
