### ISSUE TITLE
Send api-key when post customer info from Maxcdd role

### ISSUE THREAD

**Issue by munmin2000** [vrsumitha/maxmoney-agent#70]

**Comment by vrsumitha** [comment]
fixed and ready for testing

**Comment by donkhan** [comment]
send it as part of headers

**Comment by vrsumitha** [comment]
api-key added in the header request

**Comment by munmin2000** [comment]
working as expected

**Comment by vrsumitha** [comment]
merged to master and tested in master

**Comment by vrsumitha** [comment]
please test from the master and close it

**Comment by munmin2000** [comment]
working as expected in master
