### ISSUE TITLE
Activate locations 

### ISSUE THREAD

**Issue by munmin2000** [vrsumitha/maxmoney-agent#74]
Fields : Country
Status
Type

**Comment by vrsumitha** [comment]
Implementation done and ready for testing

**Comment by munmin2000** [comment]
- [x] Change the size to 100
- [x] Give Permission to Finance Manager Role

**Comment by vrsumitha** [comment]
done and code updated in the branch

**Comment by munmin2000** [comment]
If location info is 100 then activate button is disabled.
**Try With Nepal Bank in api-staging**

**Comment by munmin2000** [comment]
Last issue fixed. After multiple click on activate button, click is not working.

**Comment by vrsumitha** [comment]
merged to master
