### ISSUE TITLE
Add beneficiary flow in Upload and Create account page

### ISSUE THREAD

**Issue by munmin2000** [vrsumitha/maxmoney-agent#75]
- [ ] Put the button face as Yellow

**Comment by vrsumitha** [comment]
Beneficiary page added in cdd and create customer page
code updated in the branch...

**Comment by munmin2000** [comment]
- [ ] If Beneficiary Added when Registration then change the button to Edit mode in upload and create customer page
- [ ] If Beneficiary Added in Upload page  then change the button to Edit mode the button in create customer page

**Comment by vrsumitha** [comment]
edit is not possible, because beck end to fetch the beneficiary detail is not available

**Comment by vrsumitha** [comment]
beneficiary work flow added in upload and create customer page,
code merged to master
