### ISSUE TITLE
Remove the componenet header and put the star in place holder

### ISSUE THREAD

**Issue by munmin2000** [vrsumitha/maxmoney-agent#76]

**Comment by vrsumitha** [comment]
done. code updated in the branch, please test it

**Comment by munmin2000** [comment]
Add the below code in style.css

```
::-webkit-input-placeholder {
 font-size: 14px;
 font-weight: bold;
}
```

**Comment by vrsumitha** [comment]
done, please test it

**Comment by munmin2000** [comment]
**change** the place holder text for Nationality and State

Choose Nationality * -> **Nationality** *
Choose State * -> **State** *

Working as expected.  Kindly merge it after change

**Comment by vrsumitha** [comment]
fixed code updated in the branch

**Comment by vrsumitha** [comment]
merged to master

**Comment by munmin2000** [comment]
- [ ] Place holder text in Beneficiary select INPUT missing

**Comment by vrsumitha** [comment]
placeholder added in the page

**Comment by munmin2000** [comment]
>  
> placeholder="Nationality *    "
> placeholder="State *    "

**Comment by vrsumitha** [comment]
done, please check

**Comment by munmin2000** [comment]
merge it master

**Comment by vrsumitha** [comment]
merged to master
