### ISSUE TITLE
Registration Work Flow - Search Page

### ISSUE THREAD

**Issue by munmin2000** [vrsumitha/maxmoney-agent#77]
- [x] Add Customer Search page for maxCddOfficer Role

- [x] **Flow 1**
1. Click on Customer ID
2. If Customer Status is "Approved" then land at **Create Customer** page

- [x] **Flow 2**
1. Click on Customer ID
2. If Customer Status is "Unapproved" 
3. Pre-fill Customer Name, Id / Passport Number, Income Source, Nature of Business and load images
4. Click on Next, send Approve call

**Comment by vrsumitha** [comment]
issue 77 and 79 done in this branch itself

**Comment by munmin2000** [comment]
- [x] if images already uploaded, retrieve it when land on upload page.

**Comment by vrsumitha** [comment]
stored images showing  in the cdd page

**Comment by munmin2000** [comment]
@vrsumitha In the Normal flow of MaxcddOfficer upload page broken

![image](https://user-images.githubusercontent.com/4687217/30208721-5e7dd9d2-94c7-11e7-90d7-907a7922da39.png)

![image](https://user-images.githubusercontent.com/4687217/30208748-76e40316-94c7-11e7-90d3-738f5ccf83bc.png)

**Comment by vrsumitha** [comment]
Clear the cache, then login and search the customer and goto the cdd page, it will work properly
in the middle don't reload the page.

**Comment by vrsumitha** [comment]
it will fail if the customer doesn't have the images which is fixed now

**Comment by munmin2000** [comment]
if image is already uploaded then do not validate image in upload page

**Comment by vrsumitha** [comment]
done and code updated in issue branch

**Comment by vrsumitha** [comment]
done and merged with master
