### ISSUE TITLE
Registration Work Flow - Create Customer Page

### ISSUE THREAD

**Issue by munmin2000** [vrsumitha/maxmoney-agent#79]
MaxCddOfficer search the customer and click on ID,

- [x] **Flow 1**

1. If Customer status is "Validated" then land at Create Customer Page
2. When click on "Create Customer" button send "Convert by Agent" post call only

- [x] **Flow 2**

1. If Customer status is "Approved" then land at Create Customer Page
2. When click on "Create Customer" button send "Validate " post call followed by "Convert by Agent" post call

**Comment by vrsumitha** [comment]
code duplicated for this issue in issue-77 branch itself, 
can test the issue 79 in issue-77 branch

**Comment by munmin2000** [comment]
working as expected.
