### ISSUE TITLE
Add Income Source and Nature of Business in Registration

### ISSUE THREAD

**Issue by munmin2000** [vrsumitha/maxmoney-agent#8]
Income Sources : GET  /risks/sources
Nature of Business : GET  /risks/businesses

Update user with Income and Business : PUT /users/{username}/profile

**Comment by munmin2000** [comment]
{'incomeSource': $scope.editedUser.incomeSource}
{'natureOfBusiness': $scope.editedUser.natureOfBusiness}

**Comment by vrsumitha** [comment]
done  and merged to master

**Comment by munmin2000** [comment]
working as expected
