### ISSUE TITLE
Add Mobile Modal for User search page for maxCddOfficer

### ISSUE THREAD

**Issue by munmin2000** [vrsumitha/maxmoney-agent#81]
@vrsumitha  need to discuss

**Comment by munmin2000** [comment]
POST /users/{username}/resend-welcome-message

**Comment by munmin2000** [comment]
![image](https://user-images.githubusercontent.com/4687217/30171805-88dd2770-9425-11e7-93c5-ec11a9df9315.png)

**Comment by vrsumitha** [comment]
Implementation done,  send sms won't work because back end is not available

**Comment by vrsumitha** [comment]
- send sms won't work for maxcddOfficer role, because this role does not have permission
- sending sms is working for sa account

**Comment by munmin2000** [comment]
enable resend sms button if user in active status

**Comment by vrsumitha** [comment]
done and merged with master
