### ISSUE TITLE
Implement approve user feature

### ISSUE THREAD

**Issue by vrsumitha** [vrsumitha/maxmoney-agent#9]
- list inactive user in table
- click on user will trigger popup to show user details as readonly 
- provide accept and reject in the popup
- implement accept and reject call to back-end to complete

**Comment by vteial** [comment]
done. merged to master

**Comment by vrsumitha** [comment]
- title updated
- image size updated
- requestSource param with value agent sent to backend

done. merged to master

**Comment by vteial** [comment]
working as expected
